### ISSUE TITLE
Parallel efficiency of deepflame code

### ISSUE THREAD

**Issue by maorz1998** [deepmodeling/deepflame-dev#12]
Q: The parallel efficiency of YEqn and flow (UEqn & pEqn) solving procedures is obviously reduced as the number of processors increased from 2 to 14.
![scaling_1-28](https://user-images.githubusercontent.com/57480686/179238121-a9c338a7-c696-4869-b8b7-922cabc6d903.png)

**Comment by zhixchen** [comment]
Q: To speed up DNN inference, one idea is to stack all the cell points within each compute node (since memory can be easily shared) and use parallel CPU (like openmp) or GPU to calculate for a single large matrix multiplication? @maorz1998 @OpenFOAMFans

**Comment by zhixchen** [comment]
Looks like multi-threading is a must-go for massively parallel tasks.

**Comment by xiao312** [comment]
We have explored this issue in depth and made adequate improvements. We're now closing this issue as resolved.
