### ISSUE TITLE
Running Error from Pytorch examples

### ISSUE THREAD

**Issue by Si-XU** [deepmodeling/deepflame-dev#175]
I installed deepflame following given docs and got the successful log.

![install log](https://user-images.githubusercontent.com/61867914/205858331-e715de55-86d6-46a7-8366-eba872b0be2c.png)

Then, I tested an example by following commits:

```
. install.sh
cd examples/df0DFoam/zeroD_cubicReactor/H2/pytorchIntegrator/
./Allrun
```

The error is shown in log.mpirun:

![mpirun log](https://user-images.githubusercontent.com/61867914/205858365-f25de325-e23e-4f3a-bd81-97ca21307a0b.png)

By the way, it is correct in "df0DFoam/zeroD_cubicReactor/H2/cvodeIntegratorresults".

**Comment by JX278** [comment]
According to the info you provided, the inference did not start, and the process failed to enter the python file. You can check the "inference.py" file, checking whether those modules at the front of the file are successfully imported.

**Comment by WangS195** [comment]
> Thanks for you reply, I found the problem is that I did not download DNN models.

Hello, I am very sorry to disturb you. I had the same problem with running, I downloaded the DNN model and copied it to the mechanisms folder, but it didn't solve the problem.  Could you tell me where the DNN model should be stored and how to use it in detail? Thank you very much!
