### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by ch981111** [deepmodeling/deepflame-dev#178]
您好，请问一下这个安装问题应该怎么解决
     -lm -o /home/ch/deepflame-dev/bin/df0DFoam
/usr/bin/ld.bfd: warning: libmkl_rt.so.2, needed by /home/ch/miniconda3/envs/deepflame/lib/libcantera.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld.bfd: /home/ch/miniconda3/envs/deepflame/lib/libcantera.so: undefined reference to `dgbcon_'
/usr/bin/ld.bfd: /home/ch/miniconda3/envs/deepflame/lib/libcantera.so: undefined reference to `dgbtrf_'
/usr/bin/ld.bfd: /home/ch/miniconda3/envs/deepflame/lib/libcantera.so: undefined reference to `dgetri_'
/usr/bin/ld.bfd: /home/ch/miniconda3/envs/deepflame/lib/libcantera.so: undefined reference to `dgbtrs_'
/usr/bin/ld.bfd: /home/ch/miniconda3/envs/deepflame/lib/libcantera.so: undefined reference to `dgemv_'
/usr/bin/ld.bfd: /home/ch/miniconda3/envs/deepflame/lib/libcantera.so: undefined reference to `dgetrf_'
/usr/bin/ld.bfd: /home/ch/miniconda3/envs/deepflame/lib/libcantera.so: undefined reference to `dgetrs_'
collect2: error: ld returned 1 exit status
make: *** [/opt/openfoam7/wmake/makefiles/general:142: /home/ch/deepflame-dev/bin/df0DFoam] Error 1

**Comment by JX278** [comment]
"You may come accross an error regarding shared library libmkl_rt.so.2 when libcantera is installed through cantera channel. If so, go to your conda environment and check the existance of libmkl_rt.so.2 and libmkl_rt.so.1, and then link libmkl_rt.so.2 to libmkl_rt.so.1." 这个问题在我们的用户文档里面有写。可以去https://deepflame.deepmodeling.com/en/latest/qs/install.html#build-and-install 这个链接看一下具体的。
