### ISSUE TITLE
Adjustable writeInterval 

### ISSUE THREAD

**Issue by hanli94** [deepmodeling/deepflame-dev#18]
How to add adjustable writeinterval function in controlDict? So that for some time periods (i.e., near detonation initiation and development), the writeinterval can be small enough for postprocessing.

**Comment by Han-Li-NUS** [comment]
Use several controlDict files and update controlDict automatically when running openfoam. 

For example, if a new writeinterval 1e-6 second is needed after running 2e-4 second, firstly change startFrom to latestTime. Secondly, add the following codes to controlDict, then copy it and rename the copied one to controlDict1.

functions
{
    fileUpdate1
    {
        type              timeActivatedFileUpdate;
        libs              ("libutilityFunctionObjects.so");
        writeControl      adjustableRunTime;
        writeInterval     1.0e-6;
        fileToUpdate      "$FOAM_CASE/system/controlDict";
        timeVsFile
        (
            (2.0e-4 "$FOAM_CASE/system/controlDict1")   #new writeInterval given in controlDict1 will be used after 2.0e-4 second
        );
    }
}


### Refered to https://openfoam.top/adjustableWrite/
