### ISSUE TITLE
请问这张图的结果如何复现

### ISSUE THREAD

**Issue by ch981111** [deepmodeling/deepflame-dev#182]
![2D_detonation_pMax](https://user-images.githubusercontent.com/81225909/211142572-dc5af373-d38d-4dce-a44b-7a57fc448f7e.png)

**Comment by pkuLmq** [comment]
The figure is the instantaneous maximum pressure field. To draw this picture, you need to do a little change to the solver dfHighSpeedFoam. You can get to the folder "application/solvers/dfHighSpeedFoam", then add an extra field named "pmax"(or the other name you want) in createFields.H (remember to set the readwrite switch to be NO_READ and AUTO_WRITE) and use the field p to initialise this field. Then update the pmax field every step to record the history of maximum pressure of each cell. When finish running, you can use paraview to visualise the result.

**Comment by pkuLmq** [comment]
You can add lines to update pmax field in dfHighSpeedFoam.C

**Comment by ch981111** [comment]
1.Do I need to recompile the solver after adding
2.volScalarField pmax
(
    IOobject
    (
        "pmax",
        runTime.timeName(),
        mesh,
        IOobject::NO_READ,
        IOobject::AUTO_WRITE
    ),
    max(p).value()
);
Can I use this in createFields.H and how I update pmax field in dfHighSpeedFoam.C ?
Thanks for your advice !

**Comment by xiao312** [comment]
We're closing this issue as we due to inactivity for a long time. If the issue still persists or if you have any further questions or concerns, please don't hesitate to reopen this issue or create a new one.

Thank you for reporting this issue and for your contributions to our project.
