### ISSUE TITLE
Installation Problems on Centos 7.6

### ISSUE THREAD

**Issue by lql341** [deepmodeling/deepflame-dev#2]
Has any one try install deepflame on Centos 7.6.

My configuration:

System: Centos 7.6
gcc compiler : GCC 7.3.1
MPI Compiler: OpenMPI 4.0.4

I followed the instructions 1-6 , and ran into glibc version errors at 6.
![image](https://user-images.githubusercontent.com/35156008/173972059-bc5a4b0c-0b15-4667-8f76-280223b376ff.png)

The problems are as follows:
![f9cbf729d6ca62b39f18006e542d512](https://user-images.githubusercontent.com/35156008/173972151-ce030336-0bd9-41c0-b2ec-0674bfd535cf.jpg)

I assume this require recompilation of libtorch.so instead of using precompiled ones. 

Any comments or suggestions?

**Comment by maorz1998** [comment]
It seems like a C++ ABI problem, maybe your gcc compiler is too old. Try the following three methods to solve the problem.
- The precompiled Libtorch with Pre-cxx11 ABI is also produced, install this one and have a try!
[https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-1.11.0%2Bcpu.zip](url)
- Update your gcc version (gcc 9.4.0 can install DeepFlame successfully)
- Try to compile Libtorch from source ~

**Comment by lql341** [comment]
I upgrade my gcc version to 11.2 and recompiled from scratch. I believe the problem comes from libtorch. 
![image](https://user-images.githubusercontent.com/35156008/174429286-c4644569-1ef2-4b4d-86b4-d1ed18712fd7.png)

Can you provide a tutorial for compiling Libtorch?

**Comment by maorz1998** [comment]
The tutorial here ( [https://github.com/pytorch/pytorch#from-source](url)) can be helpful, gook luck !

**Comment by lql341** [comment]
![1982_1656164305_hd](https://user-images.githubusercontent.com/35156008/175776679-7e4a4567-e1a1-4fa7-a255-29e2f332e79b.jpeg)
Done! Rebuilding libtorch from source did solve the problem. Thank you!
