### ISSUE TITLE
Thermo and Trans properties : Growing evaluation time

### ISSUE THREAD

**Issue by Shackman287** [deepmodeling/deepflame-dev#200]
Would it be possible to include run logs in your examples cases? Viewing my log file for the twoD_SandiaD_EDC_Trans case, I see the Thermo & Trans Properties is not only taking up 85% of the runtime, but it is in fact a growing percentage! This is pre-ignition. Is this expected? Also I can't seem to run it in serial, these cases must run in parallel? Thank you. DeepFlame is an amazing contribution to the OpenFOAM combustion community!

**Comment by maorz1998** [comment]
As you can see, updating the thermal properties in a simulation that lacks chemical reactions and features an uncomplicated flow is truly a time-consuming process. Essentially, it involves utilizing Newton's iterative method to calculate the temperature and computing the transport parameters using Cantera's native API, unless one opts for the simplest transport model called "UnityLewis". Nevertheless, in most cases, this aspect of the calculation does not represent a bottleneck compared to the chemical source term calculation and the PDE solution process. Hence, we have not prioritized optimizing this part of the calculation logic further at this stage. However, we recognize the importance of enhancing the efficiency of this step and are planning to utilize advanced AI and HPC methods in the future to accelerate this process.
As for your second question about running dfLowMachFoam in serial, we have fixed this bug in #185 .
Best regards.
