### ISSUE TITLE
用dfHighSpeedFoam计算二维旋转爆轰过程，不论是单核还是并行总是在这里报错停止

### ISSUE THREAD

**Issue by ch981111** [deepmodeling/deepflame-dev#219]
Mean and max Courant Numbers = 0.014369468 0.025807784
Time = 5.412e-05

diagonal:  Solving for rho, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoUx, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for rhoUy, Initial residual = 0, Final residual = 0, No Iterations 0

min / max mag(U) ; 59.474653 / 2192.2199

=== begin solve_CVODE === 
Now DLB algorithm is used!!
=== end solve_CVODE === 
DILUPBiCGStab:  Solving for H, Initial residual = 0.0021290569, Final residual = 7.7770006e-12, No Iterations 1
DILUPBiCGStab:  Solving for H2, Initial residual = 0.00019308764, Final residual = 4.9533175e-13, No Iterations 1
DILUPBiCGStab:  Solving for O, Initial residual = 0.0020087055, Final residual = 1.8896447e-14, No Iterations 2
DILUPBiCGStab:  Solving for O2, Initial residual = 0.00021835957, Final residual = 2.2889289e-12, No Iterations 1
DILUPBiCGStab:  Solving for OH, Initial residual = 0.00068543456, Final residual = 2.290911e-14, No Iterations 2
DILUPBiCGStab:  Solving for H2O, Initial residual = 0.00021665355, Final residual = 2.6371567e-12, No Iterations 1
DILUPBiCGStab:  Solving for HO2, Initial residual = 0.0044336179, Final residual = 3.987037e-14, No Iterations 2
DILUPBiCGStab:  Solving for H2O2, Initial residual = 0.0032757614, Final residual = 2.2794104e-14, No Iterations 2
diagonal:  Solving for rhoE, Initial residual = 0, Final residual = 0, No Iterations 0
[ubuntu:81136] *** Process received signal ***
[ubuntu:81136] Signal: Aborted (6)
[ubuntu:81136] Signal code:  (-6)
[ubuntu:81136] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x143c0)[0x7f3f457013c0]
[ubuntu:81136] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f3f4553e03b]
[ubuntu:81136] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f3f4551d859]
[ubuntu:81136] [ 3] /home/ch/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb135a)[0x7f3f4592c35a]
[ubuntu:81136] [ 4] /home/ch/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb13c5)[0x7f3f4592c3c5]
[ubuntu:81136] [ 5] /home/ch/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb1658)[0x7f3f4592c658]
[ubuntu:81136] [ 6] /home/ch/miniconda3/envs/deepflame/lib/libcantera.so.2(+0x1997f8)[0x7f3f4694e7f8]
[ubuntu:81136] [ 7] dfHighSpeedFoam(+0xd5a8d)[0x5645e462ea8d]
[ubuntu:81136] [ 8] dfHighSpeedFoam(+0x49632)[0x5645e45a2632]
[ubuntu:81136] [ 9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f3f4551f0b3]
[ubuntu:81136] [10] dfHighSpeedFoam(+0x4c80e)[0x5645e45a580e]
[ubuntu:81136] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node ubuntu exited on signal 6 (Aborted).

**Comment by pkuLmq** [comment]
Do you have more informaiton about that ?

**Comment by xiao312** [comment]
We're closing this issue as we due to inactivity for a long time. If the issue still persists or if you have any further questions or concerns, please don't hesitate to reopen this issue or create a new one.

Thank you for reporting this issue and for your contributions to our project.
