### ISSUE TITLE
output of error when using dfHighSpeedFoam

### ISSUE THREAD

**Issue by pkuLmq** [deepmodeling/deepflame-dev#23]
when using dfHighSpeedFoam, there will be more than 2w lines output before calculating the example.

![image](https://user-images.githubusercontent.com/93322416/181712463-716a838c-380b-4523-ac33-ec72d42eb743.png)

**Comment by zhixchen** [comment]
> The reason is that libfieldFunctionObjects.so is included in this case. Abd libfieldFunctionObjects.so depends on several libs from official OpenFOAM which causes conflicts. This can be solved by change [src/functionObjects/field/Make/options](https://github.com/OpenFOAM/OpenFOAM-7/blob/master/src/functionObjects/field/Make/options)

Create a PR?

**Comment by OpenFOAMFans** [comment]
solved by this commit: f7d6d9b7ea02934a9c26c815540e14287e765cba
