### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by starflame-Qot** [deepmodeling/deepflame-dev#254]
Hello, I'm currently having trouble trying to install deepflame. I refer to the installation guide. The result shows that the installation is successful, but all the reference cases provided cannot be run normally, regardless of whether DNN is applicable. In fact, I have installed the previous version of deepflame in the same environment, and it can at least run CVODE cases, but the DNN studies cannot be simulated.
![安装](https://user-images.githubusercontent.com/119994097/236144992-eac5d240-813f-4bcc-a2e7-8802569225d8.JPG)
This is the error I reported when running examples/df0DFoam/zeroD_cubicReactor/H2/cvodeIntegrator.
![error](https://user-images.githubusercontent.com/119994097/236147267-ab7fa8d3-006d-4b43-a042-14a35b0c4498.JPG)
 I've noticed that in my previous installations there has been a hint that the file cannot be found at the specified path as shown in the image below, is this the problem？
![问题](https://user-images.githubusercontent.com/119994097/236144999-91a09c3f-af88-4219-9a25-5fa9615faddd.JPG)

Thanks for any potential help and answers！

**Comment by xiao312** [comment]
Hi! 

Thank you for reaching out to us regarding your issue.

Regarding the error message you reported when running the reference cases, it seems that there is an issue with the mechanism files. In our reference cases, we use relative paths for symbolic links that point to mechanism files in `deepflame-dev/mechanisms`. This could potentially be the root of the problem. You may want to check the symbolic links or simply copy the desired mechanism file into the directory where you're running the cases. The same also applies to running DNN cases. Also, please ensure that the DNN models have been correctly downloaded following the instructions on [this page](https://deepflame.deepmodeling.com/en/latest/qs/download_dnn_models.html). Based on the messages shown in your terminal, I believe there should be no problems with your installation and compilation.

Please let us know if this information is helpful in resolving your issue. Thank you for your patience and cooperation.

Best regards!

**Comment by starflame-Qot** [comment]
Thanks for your reply. Currently I have version 1.1.3 installed. CVODE case works, but Pytorch case still doesn't. I have downloaded the DNN model and placed it in the mechanism folder. The error is reported as follow.


Starting time loop

--> FOAM Warning : 
    From function virtual void Foam::probes::findElements(const Foam::fvMesh&)
    in file probes/probes.C at line 138
    Location (0.0025 0.0025 0.0025) seems to be on multiple domains: cell 20 on my domain 0 and cell 224 on some other domain.
This might happen if the probe location is on a processor patch. Change the location slightly to prevent this.
--> FOAM Warning : 
    From function virtual void Foam::probes::findElements(const Foam::fvMesh&)
    in file probes/probes.C at line 152
    Location (0.0025 0.0025 0.0025) seems to be on multiple domains: cell 43 on my domain 0 and face 795 on some other domain.
This might happen if the probe location is on a processor patch. Change the location slightly to prevent this.
Courant Number mean: 0 max: 0
Time = 1e-06

=== begin solve_CVODE === 
Now DLB algorithm is used!!
=== end solve_CVODE === 
diagonal:  Solving for H, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for O, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for H2O, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for OH, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for O2, Initial residual = 0, Final residual = 0, No Iterations 0
diagonal:  Solving for H2, Initial residual = 0, Final residual = 0, No Iterations 0
========Time Spent in diffenet parts========
Chemical sources           = 0.0498818 s
Species Equations          = 0.000425 s
thermo & Trans Properties  = 0.000285 s
============================================

ExecutionTime = 0.28 s  ClockTime = 0 s
    allsolveTime = 0 s    submasterTime = 0 s
    sendProblemTime = 0 s    recvProblemTime = 0 s    sendRecvSolutionTime = 0 s
    getDNNinputsTime = 0 s    DNNinferenceTime = 0 s    updateSolutionBufferTime = 0 s
    vec2ndarrayTime = 0 s    pythonTime = 0 s

Courant Number mean: 0 max: 0
Time = 2e-06

=== begin solve_DNN === 
now DNN inference is conducted on CPU
inputsDNN0 = 250
inputsDNN1 = 0
inputsDNN2 = 0
inputsDNN0 = 250
inputsDNN1 = 0
inputsDNN2 = 0
inputsDNN0 = 250
inputsDNN1 = 0
inputsDNN2 = 0
inputsDNN0 = 250
inputsDNN1 = 0
inputsDNN2 = 0
[dyfluid:04286] *** Process received signal ***
[dyfluid:04285] *** Process received signal ***
[dyfluid:04285] Signal: Aborted (6)
[dyfluid:04285] Signal code:  (-6)
[dyfluid:04286] Signal: Aborted (6)
[dyfluid:04286] Signal code:  (-6)
[dyfluid:04285] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f5db1a40980]
[dyfluid:04285] [ 1] [dyfluid:04284] *** Process received signal ***
[dyfluid:04284] Signal: Aborted (6)
[dyfluid:04284] Signal code:  (-6)
[dyfluid:04286] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f596a86e980]
[dyfluid:04286] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f596a4a9e87]
[dyfluid:04286] [ 2] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f5db167be87]
[dyfluid:04285] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f5db167d7f1]
[dyfluid:04285] [ 3] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb135a)[0x7f5db209c35a]
[dyfluid:04285] [ 4] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f596a4ab7f1]
[dyfluid:04286] [ 3] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb135a)[0x7f596aeca35a]
[dyfluid:04286] [ 4] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb13c5)[0x7f596aeca3c5]
[dyfluid:04286] [ 5] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb1658)[0x7f596aeca658]
[dyfluid:04286] [ 6] df0DFoam(+0x4c3cf)[0x56454f5083cf]
[dyfluid:04283] *** Process received signal ***
/home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb13c5)[0x7f5db209c3c5]
[dyfluid:04285] [ 5] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb1658)[0x7f5db209c658]
[dyfluid:04285] [ 6] df0DFoam(+0x4c3cf)[0x5640e66773cf]
[dyfluid:04285] [ 7] df0DFoam(+0x4c464)[0x5640e6677464]
[dyfluid:04285] [ 8] df0DFoam(+0x905e6)[0x5640e66bb5e6]
[dyfluid:04285] [ 9] df0DFoam(+0x2ede6)[0x5640e6659de6]
[dyfluid:04285] [10] [dyfluid:04286] [ 7] df0DFoam(+0x4c464)[0x56454f508464]
[dyfluid:04286] [ 8] df0DFoam(+0x905e6)[0x56454f54c5e6]
[dyfluid:04286] [ 9] df0DFoam(+0x2ede6)[0x56454f4eade6]
[dyfluid:04286] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f596a48cc87]
[dyfluid:04286] [11] df0DFoam(+0x311ea)[0x56454f4ed1ea]
[dyfluid:04286] *** End of error message ***
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f5db165ec87]
[dyfluid:04285] [11] df0DFoam(+0x311ea)[0x5640e665c1ea]
[dyfluid:04285] *** End of error message ***
[dyfluid:04283] Signal: Aborted (6)
[dyfluid:04283] Signal code:  (-6)
[dyfluid:04283] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7fa9854d0980]
[dyfluid:04283] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7fa98510be87]
[dyfluid:04283] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7fa98510d7f1]
[dyfluid:04283] [ 3] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb135a)[0x7fa985b2c35a]
[dyfluid:04283] [ 4] [dyfluid:04284] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb13c5)[0x7fa985b2c3c5]
[dyfluid:04283] [ 5] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0/home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb1658)[0x7fa985b2c658]
[dyfluid:04283] [ 6] df0DFoam(+0x4c3cf)[0x5626e94193cf]
[dyfluid:04283] [ 7] df0DFoam(+0x4c464)[0x5626e9419464]
[dyfluid:04283] [ 8] df0DFoam(+0x905e6)[0x5626e945d5e6]
[dyfluid:04283] [ 9] df0DFoam(+0x2ede6)[0x5626e93fbde6]
[dyfluid:04283] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7fa9850eec87]
[dyfluid:04283] [11] df0DFoam(+0x311ea)[0x5626e93fe1ea]
[dyfluid:04283] *** End of error message ***
(+0x12980)[0x7f95dc0d6980]
[dyfluid:04284] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f95dbd11e87]
[dyfluid:04284] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f95dbd137f1]
[dyfluid:04284] [ 3] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb135a)[0x7f95dc73235a]
[dyfluid:04284] [ 4] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb13c5)[0x7f95dc7323c5]
[dyfluid:04284] [ 5] /home/dyfluid/miniconda3/envs/deepflame/lib/libstdc++.so.6(+0xb1658)[0x7f95dc732658]
[dyfluid:04284] [ 6] df0DFoam(+0x4c3cf)[0x5588da7fc3cf]
[dyfluid:04284] [ 7] df0DFoam(+0x4c464)[0x5588da7fc464]
[dyfluid:04284] [ 8] df0DFoam(+0x905e6)[0x5588da8405e6]
[dyfluid:04284] [ 9] df0DFoam(+0x2ede6)[0x5588da7dede6]
[dyfluid:04284] [10] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f95dbcf4c87]
[dyfluid:04284] [11] df0DFoam(+0x311ea)[0x5588da7e11ea]
[dyfluid:04284] *** End of error message ***

**Comment by xiao312** [comment]
To better assist you with this issue, could you please provide additional details about of your placement of the DNN model?

Best regards!

**Comment by starflame-Qot** [comment]
Hello, after the current latest version is installed, the above cases can run normally, the only problem is that when the GPU switch is turned on, the calculation report will report an error, which should be related to my use of virtual machine and GPU driver. Thanks for your help.
