### ISSUE TITLE
. configure.sh --use_pytorch配置出问题

### ISSUE THREAD

**Issue by ann25** [deepmodeling/deepflame-dev#263]
您好，我在1.2configure上遇到了问题。pytorch已经安装好，cuda也可以使用。但是在. configure.sh --use_pytorch 这一步中出现了以下的问题
![图片](https://github.com/deepmodeling/deepflame-dev/assets/129950334/2ad6be37-2fed-4386-b358-45eb433a5523)
请问该怎么解决呢

**Comment by ann25** [comment]
/home/an/Pictures/2023-05-19 21-07-09屏幕截图.png
在pytorch环境下也不成功

**Comment by ann25** [comment]
不好意思，上面的问题已经解决了。但是在. install.sh这一步出现了新的问题。请问这个要怎么解决呢。前面的步骤都是按照说明手册安装的
![2023-05-19 21-07-09屏幕截图](https://github.com/deepmodeling/deepflame-dev/assets/129950334/d26a4240-4397-4f79-87c8-8f90b4762c2d)


> Hi!
> 
> Thank you for contacting us about your issue.
> 
> Based on the information provided, it appears that DeepFlame is unable to locate your local PyTorch libraries. To better assist you with this issue, could you please provide additional details about how you installed PyTorch and DeepFlame? Having this information will enable us to investigate the issue further and work towards finding a resolution.
> 
> Thank you for your patience as we work to resolve this issue for you.
> 
> Best regards!

**Comment by ann25** [comment]
不好意思，上面的问题已经解决了。但是在. install.sh这一步出现了新的问题。前面都是跟着说明手册安装的
![2023-05-25 11-36-28屏幕截图](https://github.com/deepmodeling/deepflame-dev/assets/129950334/11fd475d-915e-4dd3-b0ec-b69cc7017380)

**Comment by mingcheng1208** [comment]
> ![2023-05-19 21-07-09屏幕截图](https://user-images.githubusercontent.com/129950334/239546512-070a25a7-fab9-4639-8a09-cc9c2a9fdc17.png) 在pytorch环境下也不成功

你好，我也遇到了这个问题，想请教一下你是怎么解决这个问题的（我也是按照向导安装的），感谢！
