### ISSUE TITLE
1.3. Build and Install 配置出问题

### ISSUE THREAD

**Issue by ann25** [deepmodeling/deepflame-dev#296]
您好，我在1.3. Build and Install 上遇到了问题。pytorch已经安装好，cuda也可以使用。前面所有步骤都是跟着安装手册安装的。但是在. install.sh这一步出现了新的问题。
![2023-05-25 11-36-28屏幕截图](https://github.com/deepmodeling/deepflame-dev/assets/129950334/2555ab30-b3c9-49a4-8cc6-9a15317d7325)

**Comment by xiao312** [comment]
Hi!

Sorry for the late reply. Based on the error message you provided, it seems like the problem is related to the OpenFOAM 7 installation.

To resolve this issue, I recommend checking your OpenFOAM 7 installation and ensuring that it is installed correctly. You can refer to the official OpenFOAM website for [detailed instructions](https://openfoam.org/download/7-ubuntu/) on how to download and install OpenFOAM 7 for Ubuntu.

**Comment by xiao312** [comment]
In my installation of OpenFOAM 7, `NSRDSfunc2.C` looks like this:
![image](https://github.com/deepmodeling/deepflame-dev/assets/121787251/1f5f1c70-2f22-4e95-8c14-2b8ec2538c7f)

**Comment by ann25** [comment]
> Hi!
> 
> Sorry for the late reply. Based on the error message you provided, it seems like the problem is related to the OpenFOAM 7 installation.
> 
> To resolve this issue, I recommend checking your OpenFOAM 7 installation and ensuring that it is installed correctly. You can refer to the official OpenFOAM website for [detailed instructions](https://openfoam.org/download/7-ubuntu/) on how to download and install OpenFOAM 7 for Ubuntu.


Thank you for your reply. My OpenFOAM was installed according to the official tutorial. I just checked that it is usable.
Besides openfoam7, l also installed v2206. Maybe it causes problems?

**Comment by ann25** [comment]
> In my installation of OpenFOAM 7, `NSRDSfunc2.C`

In my installation of OpenFOAM 7, NSRDSfunc2.C also looks like this
![2023-06-27 19-33-17屏幕截图](https://github.com/deepmodeling/deepflame-dev/assets/129950334/1a343752-b176-445f-8f63-f2d4f054caf1)

**Comment by ann25** [comment]
> In my installation of OpenFOAM 7, `NSRDSfunc2.C`

In my installation of OpenFOAM 7, NSRDSfunc2.C also looks like this
![2023-06-27 19-33-17屏幕截图](https://github.com/deepmodeling/deepflame-dev/assets/129950334/1a343752-b176-445f-8f63-f2d4f054caf1)

**Comment by xiao312** [comment]
> Besides openfoam7, l also installed v2206. Maybe it causes problems?

Yes, this appears to be the problem. I've checked that v2206 uses `a_(dict.get<scalar>("a"))`. So before you start with your installation of DeepFlame, please make sure that you source the `bashrc` file of OpenFOAM 7 and `$FOAM_SRC` points to the `src` folder of OpenFOAM 7.
