### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by wanjw1996** [deepmodeling/deepflame-dev#319]
When I tried to run . **install.sh** , as I followed those instrctions in your team's DOCS (https://deepflame.deepmodeling.com/en/latest/qs/install.html#build-and-install). The error shown in the screenshot below appeared
![image](https://github.com/deepmodeling/deepflame-dev/assets/126311212/f83d1bbf-38a9-4f06-a7e2-5c016c3f27e2)
It shows that cantera-related file (**cantera/zerodim.h**) are missing, but everything in my previous steps is normal. Can you provide relevant ideas or solutions?
Many Thanks!

**Comment by YyCFD** [comment]
i have also encountered this problem,have you resolved it?

**Comment by wanjw1996** [comment]
You can check whether your conda is installed properly (https://docs.conda.io/projects/miniconda/en/latest/). And I suggest that you re-try the process.  Most of the time it works.

**Comment by YyCFD** [comment]
Thank you for your help！



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/09/2023 03:27 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [deepmodeling/deepflame-dev] Install Issue (Issue #319) |

You can check whether your conda is installed properly (https://docs.conda.io/projects/miniconda/en/latest/). And I suggest that you re-try the process. Most of the time it works.
