### ISSUE TITLE
Gulder's coefficients in PaSR combustion model

### ISSUE THREAD

**Issue by scramjetFoam** [deepmodeling/deepflame-dev#329]
Hi,

I have noticed that you have made a lot of improvements to the PaSR combustion model, which I am very interested in. At the same time, I also noticed that the default parameter is set to CH4, such as Zst and Gulder's coefficients. I am currently using H2 to study supersonic combustion. Is there a parameter setting available?

Regards.

**Comment by xiao312** [comment]
> Hi,
> 
> I have noticed that you have made a lot of improvements to the PaSR combustion model, which I am very interested in. At the same time, I also noticed that the default parameter is set to CH4, such as Zst and Gulder's coefficients. I am currently using H2 to study supersonic combustion. Is there a parameter setting available?
> 
> Regards.

Hello, thank you for your interest!
 Unfortunately, OpenFOAM tutorials do not provide Gulder's parameters for hydrogen. However, you can refer to the link below for the settings: https://www.cfd-online.com/Forums/converge/178087-gulder-coefficients-hydrogen-gas.html. 

Please feel free to ask any questions. 
Regards!

**Comment by scramjetFoam** [comment]
> > Hi,
> > I have noticed that you have made a lot of improvements to the PaSR combustion model, which I am very interested in. At the same time, I also noticed that the default parameter is set to CH4, such as Zst and Gulder's coefficients. I am currently using H2 to study supersonic combustion. Is there a parameter setting available?
> > Regards.
> 
> Hello, thank you for your interest! Unfortunately, OpenFOAM tutorials do not provide Gulder's parameters for hydrogen. However, you can refer to the link below for the settings: https://www.cfd-online.com/Forums/converge/178087-gulder-coefficients-hydrogen-gas.html.
> 
> Please feel free to ask any questions. Regards!

**Comment by scramjetFoam** [comment]
> > > Hi,
> > > I have noticed that you have made a lot of improvements to the PaSR combustion model, which I am very interested in. At the same time, I also noticed that the default parameter is set to CH4, such as Zst and Gulder's coefficients. I am currently using H2 to study supersonic combustion. Is there a parameter setting available?
> > > Regards.
> > 
> > 
> > Hello, thank you for your interest! Unfortunately, OpenFOAM tutorials do not provide Gulder's parameters for hydrogen. However, you can refer to the link below for the settings: https://www.cfd-online.com/Forums/converge/178087-gulder-coefficients-hydrogen-gas.html.
> > Please feel free to ask any questions. Regards!

Thanks. It's useful.

Regards.
