### ISSUE TITLE
3D Taylor-Green case modelName.pt not exist

### ISSUE THREAD

**Issue by skywalker610** [deepmodeling/deepflame-dev#6]
Installation is successful, tested with 0D cases, etc., however, for the 3D Taylor-Green case, modelName.pt not exist.

**Comment by skywalker610** [comment]
Update information: all torch solvers do not work, ubuntu 20.04, with conda libtorch

**Comment by zhixchen** [comment]
Hi, the "modelName.pt" file is required to run the torch solvers, which comes from off-line training of a deep neutral network. Our training code is yet to be published as we are still trying to increase its robustness. Please follow our news, it will be open-soruced as well in the near future.
