### ISSUE TITLE
Proper acknowledgement of DLBFoam in the loadbalancing class

### ISSUE THREAD

**Issue by blttkgl** [deepmodeling/deepflame-dev#80]
Hey, 

My name is Bulut Tekgül, and I am one of the developers of [DLBFoam](https://github.com/Aalto-CFD/DLBFoam), a dynamic-load balancing library for OpenFOAM developed by Aalto University, Finland. 

We recently ran into your work through your [arXiv preprint](https://arxiv.org/pdf/2210.07094.pdf) and was excited to see our work being adopted by other researchers. However, upon browsing the DeepFlame repository we realized that the work we have done with DLBFoam was not merely adopted, but entirely copied from our code. [Here](https://github.com/deepmodeling/deepflame-dev/tree/master/src/dfChemistryModel/loadBalancing) you can see the [identical file structure](https://github.com/Aalto-CFD/DLBFoam/tree/v1.1_OF9/src/thermophysicalModels/chemistryModel/loadBalancing) with DLBFoam. We also found [this commit](https://github.com/deepmodeling/deepflame-dev/commit/fb9111fca5c871e48e27ca695a7f2f2840c159f2#diff-2d43e1842cb886a6b25e5bd365321fc444627fda950d2dd5e7fce765e6831095) that effectively removing the affiliation of this code with its original owners, which is a clear GPL violation. 

We are opening this issue on your repository to let you know that we noted this violation, and kindly requesting following changes in your code to acknowledge the original owners of the the load balancing code: 

1. Acknowledging by answering to this issue that above information is correct, and the header files of the loadbalancing class were modified. Also proper acknowledgement in the published paper. 

2. Changing all headers of the loadbalancing class to include some official Aalto header text, preferably the original headers that were removed by the commit mentioned above. 

3. README should clearly state that this repository utilises a DLBFoam code with a link to the original repository. 

We are looking forward to hearing from you,

Bulut

**Comment by zhixchen** [comment]
Hi Bulut, 

Thank you for bring up this issue and we are glad this happened before our first release v1.0 scheduled early next month. Our team are looking into this issue and will make appropriate code changes, acknowledgement and the link to the DLBFoam repo in the next pre-release v0.5 later this week. 

A formal anwser to your above questions will also be provided here in this issue conversation.  

Best regards,

The DeepFlame Team

**Comment by zhixchen** [comment]
We have now amended our code and documentation to resolve the issues raised above, which we believe will have fulfilled the three detailed requests. 

Thanks again for opening this issue and please do let us know if you have further quries.
